AWSTemplateFormatVersion: 2010-09-09
Description: Part 1 - Create Budgets with CloudFormation

Resources:
  BudgetMonthly:
    Type: AWS::Budgets::Budget
    Properties:
      Budget:
        BudgetLimit:
          Amount: 2.0
          Unit: USD
        BudgetName: BUDGET_MONTHLY
        BudgetType: COST
        TimeUnit: MONTHLY
      NotificationsWithSubscribers:
        - Notification:
            ComparisonOperator: GREATER_THAN
            NotificationType: ACTUAL
            Threshold: 50
            ThresholdType: PERCENTAGE
          Subscribers:
            - SubscriptionType: EMAIL
              Address: "email@gmail.com"